---
shamir: false
keybase_team: dockpack.vault
kbt:
  - basmeijer
  - fbezema
  - ksatirli
  - ferhaty
vault_credentials: '/Volumes/Keybase/team/dockpack.vault/vault.json'
vault_bin_path: /usr/bin
consul_bin_path: /usr/bin
boundary_tls_ca_file: consul-agent-ca.pem
boundary_tls_cert_file: dc1-client-consul-0.pem
boundary_tls_key_file: dc1-client-consul-0-key.pem


boundary_psql_endpoint: client.consul
boundary_psql_username: "{{ vault_postgres_user }}"
boundary_psql_password: "{{ vault_postgres_pass }}"
boundary_kms_type: 'transit'  # vault
vault_tls_ca_file: consul-agent-ca.pem
