#!/usr/bin/env ansible-playbook

- name: Run Audit 
  hosts: bastion
  gather_facts: false
  become: true
  vars:
    rhelcis_audit_level: 1
    ciscat: ciscat-full-bundle-2017-11-06-v3.0.44.zip
    member_dir: '/usr/local/share/CIS'
    install_dir: '/root'

  tasks:
    - name: Add unzip for Ansible unarchive module
      yum:
        name: unzip
        state: present

    - name: Add openscap-scanner
      yum:
        name: openscap-scanner
        state: present
      tags:
        - openscap

    - name: Ignore the rest when you are not a CIS Member
      unarchive:
        src: "{{ member_dir }}/{{ ciscat }}"
        dest: "{{ install_dir }}"
        creates: "{{ install_dir  }}/cis-cat-full/CIS-CAT.sh"
      ignore_errors: true

    - name: Checking if CISCAT was installed
      stat:
        path: "{{ install_dir  }}/cis-cat-full/CIS-CAT.sh"
      changed_when: false
      failed_when: false
      check_mode: false
      register: rhelcis7_ciscat

    - name: Ensure /root/CIS-CAT_Results/ exists
      when: rhelcis7_ciscat.stat.exists
      file:
        path: /root/CIS-CAT_Results/
        state: directory
        mode: 0700

    - name: Ensure previous reports are absent
      file:
        path: "/tmp/inventory_hostname"
        state: absent

    - name: Add Java to run security audit
      when: rhelcis7_ciscat.stat.exists
      yum:
        name: java-1.8.0-openjdk-headless.x86_64
        state: present

    - name: chmod script
      when: rhelcis7_ciscat.stat.exists
      file:
        path: "{{ install_dir  }}/cis-cat-full/CIS-CAT.sh"
        mode: 0700
        owner: root
        group: root

    - name: Run CIS_CAT
      when: rhelcis7_ciscat.stat.exists
      shell: './CIS-CAT.sh -a -t -rn report -b "`pwd`/benchmarks/CIS_CentOS_Linux_7_Benchmark_v2.1.1-xccdf.xml" -p xccdf_org.cisecurity.benchmarks_profile_Level_{{ rhelcis_audit_level }}_-_Server'
      args:
        chdir: "{{ install_dir }}/cis-cat-full"

    - name: Move the html report
      when: rhelcis7_ciscat.stat.exists
      shell: "mv -f /root/CIS-CAT_Results/*/report.html /tmp/report.html"
      args:
        warn: false

    - name: Get the report
      fetch:
        src: /tmp/report.html
        dest: /Users/Shared/
        flat: true
      tags:
        - fetch
      
    - name: Clear the reports
      when: rhelcis7_ciscat.stat.exists
      shell: "rm -rf /root/CIS-CAT_Results/*"

...
