#!/usr/bin/env ansible-playbook
---

- name: Provision Secure Shell with CA Signed Keys
  hosts: all
  become: true

  roles:
    - {role: dockpack.base_epel, tags: epel}
    - {role: dockpack.secure_ssh, tags: ssh}
    - {role: dockpack.hardened7, tags: harden}
    - {role: dockpack.ansible-auditd, tags: auditd}
    - {role: dockpack.base_nettime, tags: 'nettime'}
    - {role: dockpack.base_rsyslog, tags: 'syslog'}
    - {role: dockpack.base_crontab, tags: 'crontab'}
