#!/usr/bin/env ansible-playbook
---
# https://www.hashicorp.com/resources/painless-password-rotation-hashicorp-vault

- name: Password Rotation Vault Plugin
  hosts: vault_instances
  become: true

  roles:
    - role: vault-secrets-gen
      tags:
        - plugin

- name: Password Rotation Vault Plugin
  hosts: all
  become: true

  roles:
    - role: painless-password-rotation
      environment:
        VAULT_TOKEN: "{{ lookup('env','VAULT_TOKEN') }}"
