#!/usr/bin/env ansible-playbook
---

- name: Provision Secure Shell with CA Signed Keys
  hosts: jumphost
  become: true

  roles:
    - {role: dockpack.base_epel, tags: epel}
    - {role: dockpack.secure_ssh, tags: ssh}
    - {role: dockpack.hardened7, tags: harden}
    - {role: dockpack.ansible-auditd, tags: auditd}
