#!/usr/bin/env ansible-playbook
---

- name: Enable hosts with python API
  hosts: consul_instances
  become: true

  roles:
    - role: dockpack.base_python
      vars:
        python_epel:
          - python-pip
      tags: python

  post_tasks:
    - name: install python libraries
      command: "/opt/rh/rh-python36/root/usr/bin/pip3 install {{ item }}"
      with_items:
        - python-consul
        - dnspython
        - hvac
      tags:
        - python

- name: Prepare firewalld
  hosts: consul_instances:vault_instances
  become: true

  roles:
    - role: firewalld
      tags: firewalld

- name: Provision Consul
  hosts: consul_instances
  become: true

  roles:
    - role: dockpack.base_epel
    - role: ansible-consul
      vars:
        consul_acl_enable: true
        consul_acl_default_policy: 'deny'
        consul_acl_master_token_display: true
      tags: consul
    - role: consul-policies
      tags: consul_policies

- name: Provision Hashicorp Vault
  hosts: vault_instances
  become: true
  become_user: root
  vars:
    consul_config_path: "/etc/consul"
    consul_debug: true
  pre_tasks:
    - name: Read ACL master token from first Consul server
      delegate_to: "{{ groups.consul_instances[0] }}"
      command: "cat {{ consul_config_path }}/config.json"
      register: config_read
      no_log: true
      changed_when: false
      run_once: true
      tags: 'vault'

    - name: Save ACL master token from Consul configuration
      set_fact:
        vault_consul_token: "{{ config_read.stdout | from_json | json_query(query) }}"
      vars:
        query: "acl.tokens.master"
      no_log:  true
      tags: 'vault'

  roles:
    - role: ansible-vault
      tags: 'vault'

    - role: vault-admin
      tags: 'vault_admin'

    - role: dockpack.keybase_unseal
      tags: 'unseal'

    - role: vault-engines
      tags: 'vault_engines'
    - role: vault-policies
      tags: 'vault_policies'

- name: Create boundary backend
  hosts: client
  become: true
  vars_files:
    - roles/ansible-vault/defaults/main.yml

  pre_tasks:

    - name: load encrypted Vault credentials
      become: false
      delegate_to: localhost
      run_once: true
      no_log: true
      shell: "ansible-vault view {{ vault_credentials }} |jq -r .root_token"
      register: json
      tags:
        - boundary
 
    - name: set root_token
      delegate_to: localhost
      run_once: true
      no_log: true
      set_fact:
        root_token: "{{ json.stdout }}"
      tags:
        - boundary

  roles:
    - role: dockpack.base_epel
    - role: cogini.postgresql-ssl
      tags: 'postgres'
      vars:
        postgresql_ca_subj_base: "/C=NL/O=Dockpack"
        postgresql_ca_server_ca_pass: "{{ vault_ca_secret }}" # set this in vault
        postgresql_ca_hostname_fqdn: client.consul
        postgresql_ca_group: root
    - role:  dockpack.base_postgres
      tags: 'postgres'
      vars:
        postgresql_ssl: 'on'
        postgresql_ssl_cert_file: "/etc/ssl/postgresql/server.crt"
        postgresql_ssl_key_file: "/etc/ssl/postgresql/server.key"
        postgresql_ssl_ca_file: "/etc/ssl/postgresql/root.crt"
    - role: arctiqjacob-boundary
      environment:
        VAULT_TOKEN: "{{ root_token }}"
      vars:
        boundary_kms_type: 'transit'
      tags: 'boundary'

- name: Create bastion enclave
  hosts: bastion
  become: true
  roles:
    - role: leonallen22.ansible_role_keybase
    - role: dockpack.gpg_agent
    - role: dockpack.secure_ssh

