#!/usr/bin/env ansible-playbook
---

- name: Provision Consul
  hosts: consul_instances
  become: true

  roles:
    - role: dockpack.base_epel
    - role: ansible-consul
      vars:
        consul_acl_enable: true
        consul_acl_default_policy: 'deny'
      tags: consul

- name: Provision Hashicorp Vault
  hosts: vault_instances
  become: true
  become_user: root
  vars:
    consul_config_path: "/etc/consul"
  pre_tasks:
    - name: Read ACL master token from first Consul server
      delegate_to: "{{ groups.consul_instances[0] }}"
      command: "cat {{ consul_config_path }}/config.json"
      register: config_read
      no_log: trues
      run_once: true

    - name: Save ACL master token from Consul configuration
      set_fact:
        vault_consul_token: "{{ config_read.stdout | from_json | json_query(query) }}"
      vars:
        query: "acl.tokens.master"
      no_log:  true

  roles:
    - role: ansible-vault
      tags: 'vault'
