#!/usr/bin/env ansible-playbook
---

- name: Provision Consul
  hosts: consul_instances
  become: true


  roles:
    - {role: dockpack.base_epel, tags: epel}
    - {role: ansible-consul, tags: consul}

- name: Provision Hashicorp Vault
  hosts: vault_instances
  become: true
  become_user: root
  roles:
    - {role: ansible-vault, tags: ['vault']}
