---

- name: Insert http(s) export in dotfile
  lineinfile:
    path: '/etc/profile.d/vault.sh'
    line: "export VAULT_ADDR=https://{{ groups.vault_instances[0] }}:{{ vault_port }}"
    create: true
  when:
    - ansible_os_family != 'Windows'
  tags:
    - init
    - config

- name: Insert CA cert export in dotfile
  lineinfile:
    path: '/etc/profile.d/vault.sh'
    line: "export VAULT_CACERT={{ vault_tls_config_path }}/{{ vault_tls_ca_file }}"
    create: true
  when:
    - ansible_os_family != 'Windows'
  tags:
    - init
    - config

- name: Vault API reachable?
  # Attempt to help with long lines > 160 issues
  vars:
    vault_addr_protocol: "{{ vault_tls_disable | ternary('http', 'https') }}"
    vault_addr: "{{ (vault_address == '0.0.0.0') | ternary('127.0.0.1', vault_address) }}"
  uri:
    validate_certs: "{{ validate_certs_during_api_reachable_check | bool }}"
    url: "{{ vault_addr_protocol }}://{{ vault_addr }}:{{ vault_port }}/v1/sys/health"
    method: GET
    # 200 if initialized, unsealed, and active
    # 429 if unsealed and standby
    # 472 if data recovery mode replication secondary and active
    # 473 if performance standby
    # 501 if not initialized
    # 503 if sealed
    # See: https://www.vaultproject.io/api/system/health.html
    status_code: 200, 503, 200, 429, 473, 501, 503
    body_format: json
  register: check_result
  retries: 6
  until: check_result is succeeded
  delay: 10
  changed_when: false
  tags:
    - check_vault
    - init
    - unseal
    - seal

- name: Vault status
  debug:
    msg: "Vault is {{ item.value }}"
  loop: "{{ lookup('dict', vault_http_status) }}"
  when: "'{{ check_result.status }}' in item.key"
  tags:
    - check_vault
    - init
    - unseal
    - seal

- name: initialize Hashicorp Vault
  delegate_to: "{{ groups.vault_instances[0] }}"
  run_once: true
  when: "'{{ check_result.status }}' == '501'"
  no_log: true
  environment:
    VAULT_ADDR: "https://{{ groups.vault_instances[0] }}:{{ vault_port }}"
    VAULT_CACERT: "{{ vault_tls_config_path }}/{{ vault_tls_ca_file }}"
  command: vault operator init -format=json
  register: inited
  tags:
    - init

- name: save Vault credentials as pretty JSON
  delegate_to: localhost
  become: false
  no_log: true
  when: "'{{ check_result.status }}' == '501'"
  copy:
    dest: "{{ vault_credentials }}"
    content: "{{ inited.stdout|from_json|to_nice_json }}"
    mode: 0600
  register: save_json
  tags:
    - init

- name: encrypt pretty JSON with ansible-vault
  delegate_to: localhost
  become: false
  no_log: true
  when: "'{{ check_result.status }}' == '501'"
  environment:
    ANSIBLE_VAULT_PASSWORD_FILE: "{{ lookup('env','ANSIBLE_VAULT_PASSWORD_FILE') }}"
  command: "ansible-vault encrypt {{ vault_credentials }}"
  tags:
    - init

- name: Vault API reachable?
  # Attempt to help with long lines > 160 issues
  vars:
    vault_addr_protocol: "{{ vault_tls_disable | ternary('http', 'https') }}"
    vault_addr: "{{ (vault_address == '0.0.0.0') | ternary('127.0.0.1', vault_address) }}"
  uri:
    validate_certs: "{{ validate_certs_during_api_reachable_check | bool }}"
    url: "{{ vault_addr_protocol }}://{{ vault_addr }}:{{ vault_port }}/v1/sys/health"
    method: GET
    # 200 if initialized, unsealed, and active
    # 429 if unsealed and standby
    # 472 if data recovery mode replication secondary and active
    # 473 if performance standby
    # 501 if not initialized
    # 503 if sealed
    # See: https://www.vaultproject.io/api/system/health.html
    status_code: 200, 503, 200, 429, 473, 501, 503
    body_format: json
  register: check_result
  retries: 6
  until: check_result is succeeded
  delay: 10
  changed_when: false
  tags:
    - unseal
    - seal

- name: load encrypted Vault credentials
  no_log: true
  include_vars: "{{ vault_credentials }}"
  tags:
    - unseal
    - seal

- name: 'unseal Hashicorp Vault with tags=unseal'
  delegate_to: "{{ groups.vault_instances[0] }}"
  run_once: true
  no_log: true
  when: "'{{ check_result.status }}' == '503'"
  environment:
    VAULT_ADDR: "https://{{ groups.vault_instances[0] }}:{{ vault_port }}"
    VAULT_CACERT: "{{ vault_tls_config_path }}/{{ vault_tls_ca_file }}"
  command: "vault operator unseal {{ item }}"
  with_items: "{{ unseal_keys_hex }}"
  tags:
    - unseal

- name: 'seal Hashicorp Vault with tags=seal -e seal=true'
  delegate_to: "{{ groups.vault_instances[0] }}"
  run_once: true
  no_log: true
  when: seal is defined
  environment:
    VAULT_ADDR: "https://{{ groups.vault_instances[0] }}:{{ vault_port }}"
    VAULT_CACERT: "{{ vault_tls_config_path }}/{{ vault_tls_ca_file }}"
    VAULT_TOKEN: "{{ root_token }}"
  command: "vault operator seal"
  tags:
    - seal

- name: check presence of audit.log
  delegate_to: "{{ groups.vault_instances[0] }}"
  run_once: true
  stat:
    path: /var/log/vault/audit.log
  register: audit_file
  tags:
    - audit

- name: audit.log for Hashicorp Vault
  delegate_to: "{{ groups.vault_instances[0] }}"
  run_once: true
  no_log: true
  when: not audit_file.stat.exists
  environment:
    VAULT_ADDR: "https://{{ groups.vault_instances[0] }}:{{ vault_port }}"
    VAULT_CACERT: "{{ vault_tls_config_path }}/{{ vault_tls_ca_file }}"
    VAULT_TOKEN: "{{ root_token }}"
  command: >
    vault audit enable -path="vault_audit_1" file \
    file_path=/var/log/vault/audit.log
  tags:
    - audit
...
