---

- name: Enable access in firewalld
  firewalld:
    port: '{{ item }}/tcp'
    permanent: true
    state: enabled
    immediate: true
  with_items:
    - 8200
  tags:
    - firewalld

- name: Insert http(s) export in dotfile
  lineinfile:
    path: '/etc/profile.d/vault.sh'
    line: "export VAULT_ADDR=https://{{ groups.vault_instances[0] }}:{{ vault_port }}"
    create: true
  when:
    - ansible_os_family != 'Windows'
  tags:
    - init
    - config

- name: Insert CA cert export in dotfile
  lineinfile:
    path: '/etc/profile.d/vault.sh'
    line: "export VAULT_CACERT={{ vault_tls_config_path }}/{{ vault_tls_ca_file }}"
    create: true
  when:
    - ansible_os_family != 'Windows'
  tags:
    - init
    - config

- name: check presence of audit.log
  delegate_to: "{{ groups.vault_instances[0] }}"
  run_once: true
  stat:
    path: /var/log/vault/audit.log
  register: audit_file
  tags:
    - audit

- name: audit.log for Hashicorp Vault
  delegate_to: "{{ groups.vault_instances[0] }}"
  run_once: true
  no_log: true
  when: not audit_file.stat.exists
  environment:
    VAULT_ADDR: "https://{{ groups.vault_instances[0] }}:{{ vault_port }}"
    VAULT_CACERT: "{{ vault_tls_config_path }}/{{ vault_tls_ca_file }}"
    VAULT_TOKEN: "{{ root_token }}"
  command: >
    vault audit enable -path="vault_audit_1" file \
    file_path=/var/log/vault/audit.log
  tags:
    - audit
...
