#!/usr/bin/env ansible-playbook
---

- name: Provision Consul
  hosts: consul_instances
  become: true

  vars:
    consul_iface: eth1
    consul_datacenter: "dc1"
    consul_acl_datacenter: "dc1"
    # this demo only has consul servers
    consul_node_role: server
    consul_bootstrap_expect: true
    consul_domain: "consul"
    # DNS resolvers
    consul_recursors: ['8.8.4.4', '8.8.8.8']
    consul_dnsmasq_enable: true
    consul_dnsmasq_servers:
      - 8.8.4.4
      - 8.8.8.8
    # TLS
    consul_tls_enable: true
    consul_tls_src_files: files
    consul_tls_ca_crt: consul-agent-ca.pem
    consul_tls_server_crt: dc1-server-consul-0.pem
    consul_server_key: dc1-server-consul-0-key.pem
    # Constants:
    consul_client_address: "0.0.0.0"
    consul_acl_master_token_display: true
    consul_disable_update_check: true

    ### Extra ports configuration
    consul_ports_https: 8501

  roles:
    - {role: install-epel, tags: epel}
    - {role: ansible-consul, tags: consul}

  post_tasks:
    - name: install python-consul
      pip:
        name: python-consul
        state: present
      tags:
        - consul

- name: Provision Hashicorp Vault
  hosts: vault_instances
  become: true
  become_user: root
  vars:
    # VARIABLES TO EDIT
    vault_iface: eth1
    vault_datacenter: "dc1"
    vault_domain: "consul"
    vault_version: 1.1.3
    # TLS
    vault_tls_disable: 0
    vault_tls_src_files: files
    vault_tls_ca_file: consul-agent-ca.pem
    vault_tls_cert_file: dc1-server-consul-1.pem
    vault_tls_key_file: dc1-server-consul-1-key.pem
    validate_certs_during_api_reachable_check: false
    # CONSTANTS
    vault_ui: true
    vault_cluster_disable: true
  roles:
    - {role: ansible-vault, tags: ['vault']}
